### ISSUE TITLE
Model types

### ISSUE THREAD

**Issue by steffilazerte** [AdamCSmithCWS/bbsStanBayes#1]
Hi @AdamCSmithCWS, I have a quick question about the stan models.

RIght now I'm working with these (you'll note I've adjusted some of the file names, but nothing major).
```
 model      variant file                          
  <chr>      <chr>   <chr>                         
1 first_diff nonhier first_diff_nonhier_bbs_CV.stan
2 first_diff hier    first_diff_hier_bbs_CV.stan   
3 first_diff spatial first_diff_spatial_bbs_CV.stan
4 gam        hier    gam_hier_bbs_CV.stan          
5 gam        spatial gam_spatial_bbs_CV.stan       
6 gamye      hier    gamye_hier_bbs_CV.stan        
7 gamye      spatial gamye_spatial_bbs_CV.stan     
8 slope      hier    slope_hier_bbs_CV.stan        
9 slope      spatial slope_spatial_bbs_CV.stan    
```

But that leaves three gamye models which are unaccounted for:
- `gamye_O1_bbs_CV.stan`
- `gamye_OExp_bbs_CV.stan`
- `gamye_simple_bbs_CV.stan`

Are these important?

**Comment by AdamCSmithCWS** [comment]
Ah, sorry. Those extra 3 can be ignored. I've been playing with some of Stan's auto optimization options, and they were test-cases.

A

From: Steffi LaZerte ***@***.***>
Sent: October 13, 2022 5:18 PM
To: AdamCSmithCWS/bbsStanBayes ***@***.***>
Cc: Adam C Smith ***@***.***>; Mention ***@***.***>
Subject: [AdamCSmithCWS/bbsStanBayes] Model types (Issue #1)


Hi @AdamCSmithCWS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdamCSmithCWS&data=05%7C01%7CAdam.Smith%40ec.gc.ca%7Cac7f69b9c5104128a7d408daad607860%7C740c5fd36e8b41769cc9454dbe4e62c4%7C0%7C0%7C638012927097148512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vnOayC57AlDas2CB0jACm2HtaygW37UvznIRtBZSmEI%3D&reserved=0>, I have a quick question about the stan models.

RIght now I'm working with these (you'll note I've adjusted some of the file names, but nothing major).

 model      variant file

  <chr>      <chr>   <chr>

1 first_diff nonhier first_diff_nonhier_bbs_CV.stan

2 first_diff hier    first_diff_hier_bbs_CV.stan

3 first_diff spatial first_diff_spatial_bbs_CV.stan

4 gam        hier    gam_hier_bbs_CV.stan

5 gam        spatial gam_spatial_bbs_CV.stan

6 gamye      hier    gamye_hier_bbs_CV.stan

7 gamye      spatial gamye_spatial_bbs_CV.stan

8 slope      hier    slope_hier_bbs_CV.stan

9 slope      spatial slope_spatial_bbs_CV.stan

But that leaves three gamye models which are unaccounted for:

  *   gamye_O1_bbs_CV.stan
  *   gamye_OExp_bbs_CV.stan
  *   gamye_simple_bbs_CV.stan

Are these important?

-

**Comment by steffilazerte** [comment]
Thanks! That's what I assumed!
